using FluentAssertions;
using Xunit;

namespace LeetCode.Exercise;

public class ExerciseTests
{
    [Theory]
    [InlineData("I", 1)]
    [InlineData("II", 2)]
    [InlineData("III", 3)]
    [InlineData("IV", 4)]
    [InlineData("V", 5)]
    [InlineData("VI", 6)]
    [InlineData("VII", 7)]
    [InlineData("VIII", 8)]
    [InlineData("IX", 9)]
    [InlineData("X", 10)]
    [InlineData("XI", 11)]
    [InlineData("XII", 12)]
    [InlineData("XIII", 13)]
    [InlineData("XIV", 14)]
    [InlineData("XV", 15)]
    [InlineData("XVI", 16)]
    [InlineData("XVII", 17)]
    [InlineData("XVIII", 18)]
    [InlineData("XIX", 19)]
    [InlineData("XX", 20)]
    [InlineData("XXI", 21)]
    [InlineData("XXIV", 24)]
    [InlineData("XXVII", 27)]
    [InlineData("XXIX", 29)]
    [InlineData("XXX", 30)]
    [InlineData("XXXIV", 34)]
    [InlineData("XXXVIII", 38)]
    [InlineData("XXXIX", 39)]
    [InlineData("XL", 40)]
    [InlineData("XLI", 41)]
    [InlineData("XLIV", 44)]
    [InlineData("XLV", 45)]
    [InlineData("XLVIII", 48)]
    [InlineData("XLIX", 49)]
    [InlineData("L", 50)]
    [InlineData("LI", 51)]
    [InlineData("LIV", 54)]
    [InlineData("LV", 55)]
    [InlineData("LVIII", 58)]
    [InlineData("LIX", 59)]
    [InlineData("LX", 60)]
    [InlineData("LXIV", 64)]
    [InlineData("LXIX", 69)]
    [InlineData("LXX", 70)]
    [InlineData("LXXIV", 74)]
    [InlineData("LXXIX", 79)]
    [InlineData("LXXX", 80)]
    [InlineData("LXXXIV", 84)]
    [InlineData("LXXXVIII", 88)]
    [InlineData("LXXXIX", 89)]
    [InlineData("XC", 90)]
    [InlineData("XCI", 91)]
    [InlineData("XCIV", 94)]
    [InlineData("XCV", 95)]
    [InlineData("XCVIII", 98)]
    [InlineData("XCIX", 99)]
    [InlineData("C", 100)]
    [InlineData("CI", 101)]
    [InlineData("CIV", 104)]
    [InlineData("CIX", 109)]
    [InlineData("CX", 110)]
    [InlineData("CXIV", 114)]
    [InlineData("CXL", 140)]
    [InlineData("CXLIV", 144)]
    [InlineData("CL", 150)]
    [InlineData("CLVIII", 158)]
    [InlineData("CLXXXIX", 189)]
    [InlineData("CXC", 190)]
    [InlineData("CXCIX", 199)]
    [InlineData("CC", 200)]
    [InlineData("CCXLII", 242)]
    [InlineData("CCL", 250)]
    [InlineData("CCLXXVII", 277)]
    [InlineData("CCC", 300)]
    [InlineData("CCCXXXIII", 333)]
    [InlineData("CCCXCIX", 399)]
    [InlineData("CD", 400)]
    [InlineData("CDI", 401)]
    [InlineData("CDIV", 404)]
    [InlineData("CDIX", 409)]
    [InlineData("CDXL", 440)]
    [InlineData("CDXLIV", 444)]
    [InlineData("CDL", 450)]
    [InlineData("CDXC", 490)]
    [InlineData("CDXCIX", 499)]
    [InlineData("D", 500)]
    [InlineData("DI", 501)]
    [InlineData("DIV", 504)]
    [InlineData("DIX", 509)]
    [InlineData("DX", 510)]
    [InlineData("DXL", 540)]
    [InlineData("DL", 550)]
    [InlineData("DLVIII", 558)]
    [InlineData("DC", 600)]
    [InlineData("DCLXVI", 666)]
    [InlineData("DCC", 700)]
    [InlineData("DCCLXXVII", 777)]
    [InlineData("DCCC", 800)]
    [InlineData("DCCCLXXXVIII", 888)]
    [InlineData("DCCCXCIX", 899)]
    [InlineData("CM", 900)]
    [InlineData("CMI", 901)]
    [InlineData("CMIV", 904)]
    [InlineData("CMIX", 909)]
    [InlineData("CMX", 910)]
    [InlineData("CMXL", 940)]
    [InlineData("CMXLIV", 944)]
    [InlineData("CML", 950)]
    [InlineData("CMLVIII", 958)]
    [InlineData("CMXC", 990)]
    [InlineData("CMXCI", 991)]
    [InlineData("CMXCIV", 994)]
    [InlineData("CMXCVIII", 998)]
    [InlineData("CMXCIX", 999)]
    [InlineData("M", 1000)]
    public void Roman_should_convert_to_integer(string roman, int expected)
    {
        var sut = new Solution();

        var actual = sut.RomanToInt(roman);

        actual.Should().Be(expected);
    }
}
